<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // //请求数据
        // const p1 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         try {
        //             // throw new Error('错了');
        //             const data = [1, 2, 3, 4];
        //             console.log('请求a数据');
        //             resolve(data);
        //         } catch (e) {
        //             reject(e);
        //         }
        //     }, 2000)
        // })
        // console.log(p1);
        // //请求p1成功后的操作
        // const p2 = p1.then((data) => {
        //     console.log(data);
        //     const re = data.reduce((prev, item) => {
        //         return prev + item;
        //     });
        //     console.log(re);
        // });
        // console.log(p2);


        //请求A数据
        const p1 = new Promise((resolve, reject) => {
            setTimeout(() => {
                try {
                    throw new Error('err:错了');
                    console.log('请求a数据');
                    resolve([1, 2, 3, 4]);
                } catch (e) {
                    reject(e);
                }
            }, 2000)

        })
        console.log(p1);
        //A数据请求成功后，继续执行
        const p2= p1.then((data) => {
            //继续执行请求A成功后，请求b
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    try {
                        throw new error('err：b失败')
                        console.log('b成功');
                        resolve('b成功')
                    } catch (e) {
                        reject(e);
                    }
                    // console.log('请求b');
                    // resolve('请求b成功');
                    // reject('1');
                }, 1500)
            })
            // console.log(p3);
            // return p3;

        })
        console.log(p2);

        //catch处理失败的promise对象
        const p3 = p2.catch((e)=>{
            console.log('我错了')
        })

        //finally:成功和失败都会调用finally
    </script>
</body>

</html>